### ISSUE TITLE
showSelf parameter does not work

### ISSUE THREAD

**Issue by speicus** [opengeek/quickcrumbs#14]
Link to self is always displayed no matter what. Here's how I call the snippet:
[[QuickCrumbs? &showSelf=`0` &tpl=`mytpl`]]

The problem seems to be at line 110 of quickcrumbs.snippet.php. If $self is true, but $showSelf is empty, the condition on that line is false... and we pass directly to the next block which adds the link to the current resource via line 119.

**Comment by goldsky** [comment]
+1

**Comment by opengeek** [comment]
Sorry I missed this one for so long... fixed by #15 — will put a patch release up shortly
